default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: crowdai_development

test:
  <<: *default
  database: crowdai_test

production:
  <<: *default
  database: crowdai_production
  username: crowdai
  password: <%= ENV['CROWDAI_DATABASE_PASSWORD'] %>
