daily_digest:
  cron: "* * * * *" # execute at every minute
  class: "EmailDigestJob"
  queue: default
  args:
    digest_type: "daily"

weekly_digest:
  cron: "* * * * *" # execute at every minute
  class: "EmailDigestJob"
  queue: default
  args:
    digest_type: "weekly"
